/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#802fc3",
        "on-error-container": "#510017",
        outline: "#8c6c93",
        "primary-fixed": "#c583ff",
        "on-tertiary-container": "#4b007e",
        "primary-fixed-dim": "#bc6fff",
        "secondary-fixed": "#ebc3ff",
        "primary-container": "#c583ff",
        "on-surface-variant": "#6f5177",
        "on-tertiary-fixed-variant": "#551188",
        "surface-container-high": "#fad7ff",
        "secondary-container": "#ebc3ff",
        "on-tertiary": "#fceeff",
        secondary: "#8334b3",
        "surface-dim": "#f4c4ff",
        "tertiary-fixed-dim": "#c787fc",
        "on-secondary-container": "#6d189d",
        "tertiary-container": "#d199ff",
        error: "#b41340",
        "inverse-primary": "#b96cfd",
        "surface-container": "#fcdfff",
        "inverse-on-surface": "#b491bb",
        "on-secondary-fixed-variant": "#7726a7",
        "on-primary": "#fbefff",
        "on-surface": "#3f2447",
        "secondary-dim": "#7624a6",
        "surface-container-highest": "#f7d0ff",
        "surface-container-low": "#ffebff",
        "surface-variant": "#f7d0ff",
        "error-container": "#f74b6d",
        "surface-tint": "#802fc3",
        "on-primary-fixed-variant": "#450074",
        "error-dim": "#a70138",
        "inverse-surface": "#1b0424",
        background: "#fff3fc",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#37005f",
        "secondary-fixed-dim": "#e4b1ff",
        surface: "#fff3fc",
        "on-error": "#ffefef",
        "tertiary-dim": "#6e30a0",
        "on-background": "#3f2447",
        "tertiary-fixed": "#d199ff",
        "on-secondary-fixed": "#55007f",
        "on-tertiary-fixed": "#280046",
        "on-primary-fixed": "#000000",
        "surface-bright": "#fff3fc",
        "on-secondary": "#fdeeff",
        tertiary: "#7a3dad",
        "primary-dim": "#731eb6",
        "outline-variant": "#c5a1cc",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          "0%": { opacity: "0", transform: "translateY(-20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(128, 47, 195, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(128, 47, 195, 0.5)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        fadeInHero: {
          "0%": { opacity: "0" },
          "10%": { opacity: "1" },
          "85%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.8s ease-out",
        "fade-in-down": "fadeInDown 0.8s ease-out",
        "slide-in-left": "slideInLeft 0.8s ease-out",
        "slide-in-right": "slideInRight 0.8s ease-out",
        "scale-in": "scaleIn 0.8s ease-out",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        float: "float 3s ease-in-out infinite",
        "fade-in-hero": "fadeInHero 12s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
